
format = """
$username$hostname$directory$package$git_branch$git_status$cmd_duration
$character
"""

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[❯](bold bright-yellow)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[](bold black)"

# Disable the package module, hiding it from the prompt completely
[package]
symbol = " "
disabled = true

[username]
style_user = "purple bold"
style_root = "black bold"
format = "[\\[](bold red)[$user]($style)[@](green)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](fg:blue)[\\]](bold red) "
disabled = false

[directory]
read_only = " "
style = "bold bright-blue"
read_only_style = "red"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 8
truncation_symbol = "…/"

[git_branch]
symbol = " "
always_show_remote = true
format = "[$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = ""

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?‍"
stashed = "$"
modified = "!"
staged = '+'
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
show_notifications = true
min_time_to_notify = 10000

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
