#!/usr/bin/env sh
#
yabai -m config external_bar        all:40:0 \
                mouse_follows_focus on \
                focus_follows_mouse off \
                window_zoom_persist off \
                window_placement second_child \
                window_shadow float \
                window_opacity on \
                window_opacity_duration 0.2 \
                active_window_opacity 1.0 \
                normal_window_opacity 0.8 \
                insert_feedback_color 0xff9dd274 \
                split_ratio 0.5 \
                auto_balance off \
                mouse_modifier alt \
                mouse_action1 move \
                mouse_action2 resize \
                mouse_drop_action swap \
                top_padding 12 \
                bottom_padding 12 \
                left_padding 12 \
                right_padding 12 \
                window_gap 12

# Disable specific app from being managed by yabi
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

echo "Yabai is loaded"
