- name: Setup local workstation with TNH dotfiles.
  hosts: local
  roles:
    - role: git
      tags:
        - git

    #- role: yay
    #  tags:
    #    - yay
    
    - role: zsh
      tags:
        - zsh

    - role: neovim
      tags:
        - neovim

    - role: ranger
      tags:
        - ranger

    - role: fzf
      tags:
        - fzf

    - role: asdf
      tags:
        - asdf

    - role: docker
      tags:
        - docker

    - role: go
      tags:
        - go
