---
- name: TNH Dotfiles installation for servers and desktop environments.
  hosts: all
  tags: always
  become: true

  pre_tasks:
    - name: pre-run | [Arch] update package cache
      tags: always
      pacman:
        update_cache: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | [Debian...] update package cache
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]


- hosts: all
  tags: base
  become: true
  roles:
    - base
