---
- name: TNH Dotfiles installation for servers and desktop environments.
  tags: always
  become: true

  pre_tasks:
    - name: pre-run | [Arch] update package cache
      tags: always
      pacman:
        update_cache: yes
      changed_when: false
      when: ansible_distrobution == "Archlinux"

    - name: pre-run | [Debian...] update package cache
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distrobution in ["Debian", "Ubuntu"]
