#!/bin/sh
bspc rule -r "*"

## -- Autostart -- ##
pgrep -x sxhkd > /dev/null || sxhkd &
kill-all "picom"
picom &
feh --bg-fill /usr/share/backgrounds/archlinux/snow.jpg &

wmname LG3D

## -- Monitors -- ##
bspc monitor -d I II III IV V VI VII VIII IX X

## -- Global settings -- ##
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

## -- BSPWM colors -- ##
bspc config normal_border_color "4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

## -- BSPWM Config -- ##
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width         2
bspc config window_gap          10

## -- BSPWM rules -- ##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
