- name: Install lf.
  aur:
    use: yay
    name: lf
    state: present

- name: Install 'dragon' for drag and drop.
  aur:
    use: yay
    name: dragon-drag-and-drop
    state: present

- name: Check if lfrc exists.
  stat: path="{{ dotfiles_user_home }}/.config/lf/lfrc"
  register: lf_stat

- name: Backup lfrc.
  command: mv ~/.config/lf/lfrc ~/.config/lf/lfrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.config/lf/lfrc.bak"
  when: lf_stat.stat.exists

- name: Symlink lfrc.
  file:
    src: "{{ dotfiles_home }}/roles/lf/files/lfrc"
    dest: "{{ dotfiles_user_home }}/.config/lf/lfrc"
    state: link
