- name: users - geekson | add public key
  tags: users,geekson,ssh,keys
  authorized_key:
    user: geekson
    key: "{{ item }}"
  with_items:
    - users/geekson/ssh/geekson_id_ed25519.pub

- name: users - geekson | add sudoers file
  tags: users,geekson,system,sudo
  copy:
    src: users/sudoers_geekson
    dest: /etc/sudoers.d/geekson
    owner: root
    group: root
    mode: 0440
