- name: Install Zsh.
  aur:
    use: yay
    name: zsh
    state: present

- name: Check if oh-my-zsh is installed.
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh.
  raw: "sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

- name: Install zsh plugins.
  aur:
    use: yay
    name:
      - zsh-you-should-use
      - zsh-fast-syntax-highlighting
    state: present

- name: Check if .zshrc exists.
  stat: path="{{ dotfiles_user_home }}/.zshrc"
  register: zshrc_stat

- name: Backup .zshrc.
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Remove .zshrc.
  file:
    state: absent
    path: ~/.zshrc
  when: zshrc_stat.stat.exists

- name: Symlink .zshrc.
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link

- name: Symlink .zprofile.
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zprofile"
    dest: "{{ dotfiles_user_home }}/.zprofile"
    state: link

- name: Check if .zsh exists.
  stat: path="{{ dotfiles_user_home }}/.zsh"
  register: zsh_stat

- name: Backup .zsh folder.
  command: mv ~/.zsh ~/.zsh.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zsh.bak"
  when: zsh_stat.stat.exists

- name: Symlink .zsh.
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zsh"
    dest: "{{ dotfiles_user_home }}/.zsh"
    state: link

