---
- name: Install crontab, if it dosen't exist.
  pacman:
    name: cronie
    state: present
  become: yes

- name: enable and start Cronie service.
  systemd:
    name: cronie
    state: started
    enabled: yes
  become: yes

- name: Cron job for deleting bakup files weekly.
  cron:
    name: Automatic backup deletion.
    weekday: '0'
    job: 'find ~ -name "*.bak" -delete'

- name: Cron job for only downloading new updates.
  cron:
    name: Download new updates.
    minute: '5'
    hour: '2'
    job: yay -Syuw --noconfirm
    user: root
  become: yes
  
