- name: Install git.
  aur:
    use: yay
    name: git
    state: present

- name: Make sure global gitignore file is up to date.
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes

- name: Check if gitconfig file exists.
  stat: path="{{ dotfiles_user_home }}/.gitconfig"
  register: gitconfig_stat

- name: Backup gitconfig.
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "{{ dotfiles_user_home }}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date.
  template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
