- name: Install Docker.
  aur:
    use: yay
    name: docker
    state: present

- name: Install docker-compose.
  aur:
    use: yay
    name: go-tools
    state: present

- name: Make sure 'docker' group exists.
  group:
    name: docker
    state: present

- name: Add user to 'docker' group.
  user: 
    name: "{{ lookup('env','USER') }}"
    append: yes
    groups: docker
    state: present

