- name: Install base packages for Xmonad.
  aur:
    use: yay
    name: 
      - xmonad
      - xmonad-contrib
      - xmobar
    state: present

- name: Check if xmonad.hs exists.
  stat: path="{{ dotfiles_user_home }}/.xmonad/xmonad.hs"
  register: xmonad_stat

- name: Backup xmonad.hs.
  command: mv ~/.xmonad/xmonad.hs ~/.xmonad/xmonad.hs.bak
  args:
    creates: "{{ dotfiles_user_home }}/.xmonad/xmonad.hs.bak"
  when: xmonad_stat.stat.exists

- name: Symlink xmonad.hs.
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/xmonad.hs"
    dest: "{{ dotfiles_user_home }}/.xmonad/xmonad.hs"
    state: link

- name: Check if xmobarrc exists.
  stat: path="{{ dotfiles_user_home }}/.config/xmobar/xmobarrc"
  register: xmobar_stat

- name: Backup xmobarrc.
  command: mv ~/.config/xmobar/xmobarrc ~/.config/xmobar/xmobarrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.config/xmobar/xmobarrc.bak"
  when: xmobar_stat.stat.exists

- name: Symlink xmobarrc.
  file:
    src: "{{ dotfiles_home }}/roles/xmonad/files/xmobarrc"
    dest: "{{ dotfiles_user_home }}/.config/xmobar/xmobarrc"
    state: link
    force: yes
