- name: Install neovim.
  aur:
    use: yay
    name: 
      - neovim 
      - xclip
    state: present

- name: Check if nvim config folder exists.
  stat: path="{{ dotfiles_user_home }}/.config/nvim"
  register: neovim_stat

- name: Backup nvim config folder.
  command: mv ~/.config/nvim ~/.config/nvim.bak
  args:
    creates: "{{ dotfiles_user_home }}/.config/nvim.bak"
  when: neovim_stat.stat.exists

- name: Clone repo to nvim config folder.
  git:
    repo: "{{ git_repo }}"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    version: master
    update: yes
  when: clone_repo

- name: Symlink TNH-Nvim to nvim config folder.
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/repo"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
  when: not clone_repo


