- name: Install neovim.
  aur:
    use: yay
    name: 
      - neovim 
      - xclip
    state: present

- name: Check if neovim config folder exists.
  stat: path="{{ dotfiles_user_home }}/.config/neovim"
  register: neovim_stat

- name: Backup neovim config folder.
  command: mv ~/.config/neovim ~/.config/neovim.bak
  args:
    creates: "{{ dotfiles_user_home }}/.config/neovim.bak"
  when: neovim_stat.stat.exists

- name: Clone repo to neovim config folder.
  git:
    repo: "{{ git_repo }}"
    dest: "{{ dotfiles_user_home }}/.config/neovim"
    version: master
    update: yes
  when: clone_repo

- name: Symlink TNH-Nvim to neovim config folder.
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/repo"
    dest: "{{ dotfiles_user_home }}/.config/neovim"
    state: link
  when: not clone_repo


